sudo: false
cache: pip

language: python

python:
  - "2.7"

before_install:
  # For tests running git command
  - git config --global user.name "test"
  - git config --global user.email "test.test@test.com"

virtualenv:
  system_site_packages: true

# command to install dependencies
install:
  - pip install .
  - pip install coveralls
  - pip install flake8

# command to run tests
script:
  - flake8 . --exclude=__init__.py
  - coverage run --source git_aggregator setup.py test

after_success:
  - coveralls
